"""EyeGuard menu bar app.

Runs the detection loop on a background thread and shows live status in the macOS
menu bar — no terminal window required. Intended to be launched at login by a
LaunchAgent (see install_agent.sh) so it just runs.

The menu bar icon reflects current state:
    🟢  watching, all clear
    🟡  a suggestive (ALERT) frame seen recently
    🔴  an explicit (FLAGGED) frame seen recently
    ⚠️  not watching (error / no screen-recording permission)
"""

from __future__ import annotations

import threading
import time
from datetime import datetime
from pathlib import Path

import rumps

from .capture import ScreenCapturer
from .context import capture_context, frontmost_is_self, is_ignored
from .risk import assess
from .detector import Verdict
from .logger import FlagLogger
from .main import build_detector, load_config
from .uploader import SupabaseUploader

_BASE = Path(__file__).resolve().parent.parent

# Tinted eye logos for the menu bar, generated by build_icons.sh.
_MENUBAR_DIR = Path(__file__).resolve().parent.parent / "assets" / "menubar"
_ICON = {
    "watching": str(_MENUBAR_DIR / "eye_green.png"),
    Verdict.ALERT: str(_MENUBAR_DIR / "eye_yellow.png"),
    Verdict.FLAGGED: str(_MENUBAR_DIR / "eye_red.png"),
    "error": str(_MENUBAR_DIR / "eye_gray.png"),
}
# How long (seconds) the icon stays red/yellow after a flag before reverting.
_FLASH_SECONDS = 30


class EyeGuardApp(rumps.App):
    def __init__(self, config_path: str):
        # No Quit button — can't be turned off from the menu (tamper-resistance).
        # To stop it for maintenance: ./uninstall_agent.sh (launchctl unload).
        super().__init__("EyeGuard", icon=_ICON["watching"], template=False,
                         quit_button=None)
        self.title = None  # icon only, no text label
        self._current_icon = _ICON["watching"]

        # Run as a menu-bar accessory: no Dock icon, no Cmd-Tab entry. The .app's
        # LSUIElement flag doesn't reach the Python child that actually creates
        # the NSApplication, so set the activation policy explicitly here. This
        # removes the stray "Python" rocket icon from the Dock.
        try:
            from AppKit import NSApplication
            NSApplication.sharedApplication().setActivationPolicy_(1)  # Accessory
        except Exception:
            pass
        self.cfg = load_config(config_path)
        self._ignore = self.cfg.get("ignore", {}).get("window_title_contains", [])
        self._risk = self.cfg.get("context_risk", {})
        self._risk_on = bool(self._risk.get("enabled"))
        self._activity = self.cfg.get("activity_logging", {})
        self._activity_on = bool(self._activity.get("enabled"))

        # Shared state, written by the detection thread, read by the UI timer.
        self._lock = threading.Lock()
        self._watching = False
        self._status_text = "starting…"
        # Counts are derived from the log itself (so a wipe shows instantly,
        # no restart needed), cached by the log's mtime to avoid re-reading.
        self._counts_mtime: float | None = None
        self._counts_cache = (0, 0)
        self._last_flag_text = "none"
        self._last_flag_verdict: Verdict | None = None
        self._last_flag_time = 0.0
        self._frames_analyzed = 0
        self._screen_ok = True          # False = blind (black or frozen wallpaper)
        self._uploader = None           # set once the detection loop starts
        self._last_brightness: float | None = None
        # Frozen-capture detection: if the analyzed-frame count stops growing for
        # a long stretch while in use, we're almost certainly seeing only the
        # static desktop (no Screen Recording permission), not the live screen.
        self._frozen_since: float | None = None
        self._stop = threading.Event()

        # Menu items (updated by the timer).
        self._mi_status = rumps.MenuItem("Status: starting…")
        self._mi_counts = rumps.MenuItem("Flags: 0 red / 0 yellow")
        self._mi_last = rumps.MenuItem("Last: none")
        self._mi_diag = rumps.MenuItem("Diagnostics: …")
        self._mi_open_log = rumps.MenuItem("View live report",
                                           callback=self._open_log)
        self.menu = [self._mi_status, self._mi_counts, self._mi_last,
                     self._mi_diag, None, self._mi_open_log]

        self._thread = threading.Thread(target=self._detection_loop, daemon=True)
        self._thread.start()
        # UI updates must happen on the main thread — rumps.Timer fires there.
        self._timer = rumps.Timer(self._refresh_ui, 2)
        self._timer.start()
        # Data retention: prune now, then hourly.
        self._prune(None)
        self._prune_timer = rumps.Timer(self._prune, 3600)
        self._prune_timer.start()
        # Live report: keep the HTML fresh so the browser auto-refresh shows new
        # flags as they happen (only regenerates once the report's been opened).
        rsec = int(self.cfg.get("logging", {}).get("report_refresh_seconds", 10))
        self._report_timer = rumps.Timer(self._regen_report, rsec)
        self._report_timer.start()

    # ---- UI (main thread) ---------------------------------------------------

    def _log_counts(self) -> tuple[int, int]:
        """(red, yellow) counted from the current log file, cached by mtime so a
        wipe is reflected immediately without re-reading every refresh."""
        p = Path(self.cfg["logging"]["flag_log"])
        try:
            mt = p.stat().st_mtime
        except OSError:
            return (0, 0)  # no log file = nothing logged
        if mt == self._counts_mtime:
            return self._counts_cache
        red = yellow = 0
        try:
            with p.open() as f:
                for line in f:
                    if '"verdict": "flagged"' in line:
                        red += 1
                    elif '"verdict": "alert"' in line:
                        yellow += 1
        except OSError:
            pass
        self._counts_mtime = mt
        self._counts_cache = (red, yellow)
        return (red, yellow)

    def _refresh_ui(self, _timer):
        red, yellow = self._log_counts()
        with self._lock:
            watching = self._watching
            status = self._status_text
            last = self._last_flag_text
            last_verdict = self._last_flag_verdict
            last_time = self._last_flag_time
            screen_ok = self._screen_ok
            frames = self._frames_analyzed
            bright = self._last_brightness

        if not watching or not screen_ok:
            icon = _ICON["error"]
        elif last_verdict and (time.time() - last_time) < _FLASH_SECONDS:
            icon = _ICON.get(last_verdict, _ICON["watching"])
        else:
            icon = _ICON["watching"]
        if icon != self._current_icon:  # only swap when the state changes
            self.icon = icon
            self._current_icon = icon

        if not screen_ok:
            status = "NO SCREEN ACCESS — grant Screen Recording"
        self._mi_status.title = f"Status: {status}"
        self._mi_counts.title = f"Flags: {red} red / {yellow} yellow"
        self._mi_last.title = f"Last: {last}"
        b = f"{bright:.0f}" if bright is not None else "?"
        self._mi_diag.title = f"Diagnostics: {frames} frames · screen brightness {b}"

    def _prune(self, _timer):
        from .retention import prune
        try:
            prune(self.cfg)
        except Exception:
            pass  # retention must never crash the app
        # Wipe old images from the cloud bucket too (matches local retention).
        if self._uploader is not None:
            days = int(self.cfg.get("logging", {}).get("retention_days", 7))
            self._uploader.prune_cloud(days)

    def _report_path(self) -> Path:
        return Path(self.cfg["logging"]["flag_log"]).resolve().parent \
            / "flags_report.html"

    def _gen_report(self) -> Path:
        from .viewer import write_html_report
        log_cfg = self.cfg.get("logging", {})
        return write_html_report(
            self.cfg["logging"]["flag_log"], self._report_path(),
            days=int(log_cfg.get("retention_days", 7)),
            refresh=int(log_cfg.get("report_refresh_seconds", 10)))

    def _regen_report(self, _timer):
        # Keep the open report fresh (live feed). Only regen once it exists, i.e.
        # after the user has opened it at least once.
        try:
            if self._report_path().exists():
                self._gen_report()
        except Exception:
            pass

    def _open_log(self, _sender):
        try:
            out = self._gen_report()
        except Exception as e:
            rumps.alert(title="EyeGuard", message=f"Could not render report: {e}")
            return
        import subprocess
        subprocess.run(["open", str(out)])  # opens the live report in the browser

    # ---- cloud sync ---------------------------------------------------------

    def _build_uploader(self) -> SupabaseUploader | None:
        """Create the Supabase uploader from config, or None if disabled/unset.
        The secret is read from a local file (chmod 600), never from config."""
        sb = self.cfg.get("supabase", {})
        if not sb.get("enabled") or not sb.get("url"):
            return None
        secret_path = Path(sb.get("secret_file", ".supabase_secret"))
        if not secret_path.is_absolute():
            secret_path = _BASE / secret_path
        try:
            secret = secret_path.read_text().strip()
        except OSError:
            print(f"[uploader] no secret at {secret_path}; cloud sync off",
                  flush=True)
            return None
        if not secret:
            return None
        pending = Path(sb.get("pending_file", "pending_uploads.jsonl"))
        if not pending.is_absolute():
            pending = _BASE / pending
        up = SupabaseUploader(url=sb["url"], secret=secret,
                              pending_path=str(pending),
                              retry_seconds=int(sb.get("retry_seconds", 60)))
        up.start()
        print("[uploader] cloud sync on", flush=True)
        return up

    # ---- detection (background thread) --------------------------------------

    def _detection_loop(self):
        try:
            cap = self.cfg["capture"]
            capturer = ScreenCapturer(displays=cap["displays"],
                                      max_width=cap["max_width"],
                                      change_threshold=cap["change_threshold"])
            detector = build_detector(self.cfg, verbose=False)
            log_cfg = self.cfg["logging"]
            logger = FlagLogger(
                flag_log=log_cfg["flag_log"],
                save_flagged_frames=log_cfg.get("save_flagged_frames", False),
                flagged_frames_dir=log_cfg.get("flagged_frames_dir",
                                               "flagged_frames"),
                blur_red_frames=log_cfg.get("blur_red_frames", True),
                blur_strength=log_cfg.get("blur_strength", 50))
            uploader = self._build_uploader()
            self._uploader = uploader
            interval = cap["interval_seconds"]
        except Exception as e:
            with self._lock:
                self._watching = False
                self._status_text = f"load error: {type(e).__name__}"
            return

        with self._lock:
            self._watching = True
            self._status_text = "watching"

        last_probe = 0.0
        last_seen_count = 0
        last_growth_time = time.time()
        FROZEN_SECONDS = 120  # no new analyzed frames this long while up = blind
        # GREEN activity trail: how often to sample the active app/site, and how
        # often to re-log the SAME location (a keepalive proving continued use).
        act_sample = int(self._activity.get("sample_seconds", 20))
        act_heartbeat = int(self._activity.get("heartbeat_seconds", 300))
        last_activity = 0.0
        last_activity_loc = None
        last_activity_log = 0.0
        while not self._stop.is_set():
            try:
                for frame in capturer.capture(skip_unchanged=True):
                    result = detector.analyze(frame.image)
                    with self._lock:
                        self._frames_analyzed += 1
                    if result.verdict in (Verdict.FLAGGED, Verdict.ALERT,
                                          Verdict.REVIEW):
                        ctx = capture_context()
                        # Don't flag EyeGuard's own report/log windows.
                        if is_ignored(ctx, self._ignore):
                            continue
                        # Context-aware risk: drop safe-context noise, grade the rest.
                        grade = risk = None
                        if self._risk_on:
                            a = assess(result.verdict.value, result.reason, ctx,
                                       self._risk)
                            if not a["keep"]:
                                continue
                            grade, risk = a["grade"], a["risk"]
                        record = logger.log(result, frame.display_index,
                                            frame.image, context=ctx,
                                            grade=grade, risk=risk)
                        if uploader is not None:
                            uploader.enqueue(record)
                        self._record_flag(result.verdict, ctx)
                # Periodic blindness probe (independent of the change filter):
                # if the screen is consistently black, we lack Screen Recording.
                if time.time() - last_probe > 15:
                    last_probe = time.time()
                    bright = self._probe_brightness()
                    now = time.time()
                    with self._lock:
                        frames = self._frames_analyzed
                    if frames > last_seen_count:
                        last_seen_count = frames
                        last_growth_time = now
                    frozen = (now - last_growth_time) > FROZEN_SECONDS
                    is_black = bright is not None and bright < 4.0
                    ok = not is_black and not frozen
                    with self._lock:
                        self._last_brightness = bright
                        self._screen_ok = ok
                        self._frozen_since = (last_growth_time if frozen
                                              else None)
                    if not ok:  # only log problems, not healthy probes
                        print(f"[probe] PROBLEM brightness={bright} "
                              f"frames={frames} frozen={frozen} "
                              f"(no screen access?)", flush=True)

                # GREEN activity trail: record what app/site is active (no image)
                # so a reviewer sees everywhere the user went — a new row on each
                # change of location, plus a keepalive every heartbeat interval.
                if self._activity_on and time.time() - last_activity >= act_sample:
                    last_activity = time.time()
                    actx = capture_context()
                    app_name = actx.get("app")
                    if (app_name and not frontmost_is_self()
                            and not is_ignored(actx, self._ignore)):
                        loc = (f"{app_name}|"
                               f"{actx.get('url') or actx.get('window_title')}")
                        now2 = time.time()
                        if (loc != last_activity_loc
                                or now2 - last_activity_log >= act_heartbeat):
                            rec = logger.log_activity(actx)
                            if uploader is not None:
                                uploader.enqueue(rec)
                            last_activity_loc = loc
                            last_activity_log = now2
            except Exception as e:
                with self._lock:
                    self._watching = False
                    self._status_text = f"capture error: {type(e).__name__}"
            self._stop.wait(interval)

    @staticmethod
    def _probe_brightness() -> float | None:
        """Mean RGB brightness of the primary display, bypassing the change
        filter. ~0 means we're capturing black frames (no Screen Recording
        permission). Returns None if the probe itself fails."""
        try:
            import mss
            import numpy as np
            with mss.mss() as sct:
                shot = sct.grab(sct.monitors[1])
                arr = np.frombuffer(shot.bgra, dtype=np.uint8).reshape(-1, 4)
                return float(arr[:, :3].mean())  # exclude the alpha byte
        except Exception:
            return None

    def _record_flag(self, verdict: Verdict, ctx: dict):
        where = ctx.get("app") or "?"
        loc = ctx.get("url") or ctx.get("window_title")
        label = f"{where}" + (f" — {loc[:40]}" if loc else "")
        when = datetime.now().strftime("%H:%M")
        with self._lock:
            # Counts come from the log (_log_counts); here we only track the icon
            # flash + the "Last:" line.
            self._last_flag_verdict = verdict
            self._last_flag_time = time.time()
            self._last_flag_text = f"{when} {verdict.value} · {label}"


# Kept module-global so the lock is held for the whole process lifetime.
_LOCK_FH = None


def _acquire_single_instance() -> bool:
    """Take an exclusive lock so a second launch (e.g. clicking the Dock icon
    while the launchd agent is already running) exits instead of starting a
    second CLIP. Returns False if another instance already holds the lock."""
    global _LOCK_FH
    import fcntl
    lock_path = Path(__file__).resolve().parent.parent / ".eyeguard.lock"
    _LOCK_FH = open(lock_path, "w")
    try:
        fcntl.flock(_LOCK_FH, fcntl.LOCK_EX | fcntl.LOCK_NB)
        return True
    except OSError:
        return False


def main():
    import argparse
    p = argparse.ArgumentParser(prog="eyeguard-menubar")
    p.add_argument("--config", default=str(Path(__file__).resolve().parent.parent
                                            / "config.yaml"))
    args = p.parse_args()
    if not _acquire_single_instance():
        print("[eyeguard] another instance is already running; exiting.",
              flush=True)
        return
    EyeGuardApp(args.config).run()


if __name__ == "__main__":
    main()
